
project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE}
  banner:
    charset: ${SPRING_BANNER_CHARSET}
    location: ${SPRING_BANNER_LOCATION}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''

#Logging
logging:
  level:
    br.senac.go: debug
    org.springframework.web: info